version: "3"

services:  
  consul-master-1:
    image: consul:0.9.0
    command: agent -server -bootstrap-expect=3 -datacenter=local1 -node=consul-master-1 -bind='{{ GetInterfaceIP "eth0" }}' -client=0.0.0.0 -ui
    ports:
      - 8500:8500
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "acl_datacenter":"local1", "acl_master_token":"${CONSUL_MASTER_TOKEN}", "acl_default_policy": "deny" }'
    volumes:
      - consul-1:/consul/data
    networks:
      - netgate

  consul-master-2:
    image: consul:0.9.0
    entrypoint: consul
    command: agent -server -retry-join=consul -datacenter=local1 -node=consul-master-2 -bind='{{ GetInterfaceIP "eth0" }}' -data-dir=/consul/data -client=0.0.0.0 -dns-port=53 -recursor=8.8.8.8
    depends_on:
      - consul-master-1
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "acl_datacenter":"local1", "acl_master_token":"${CONSUL_MASTER_TOKEN}", "acl_default_policy": "deny" }'
    volumes:
      - consul-2:/consul/data
    links:
      - consul-master-1:consul
    networks:
      - netgate
      
  consul-master-3:
    image: consul:0.9.0
    entrypoint: consul
    command: agent -server -retry-join=consul -datacenter=local1 -node=consul-master-3 -bind='{{ GetInterfaceIP "eth0" }}' -data-dir=/consul/data -client=0.0.0.0 -dns-port=53 -recursor=8.8.8.8
    depends_on:
      - consul-master-1
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "acl_datacenter":"local1", "acl_master_token":"${CONSUL_MASTER_TOKEN}", "acl_default_policy": "deny" }'
    volumes:
      - consul-3:/consul/data
    links:
      - consul-master-1:consul
    networks:
      - netgate

  vault:
    image: vault:0.7.3
    command: server
    ports:
      - 8200:8200
    cap_add: 
      - IPC_LOCK 
    depends_on:
      - consul-master-1
    environment:
      - 'VAULT_LOCAL_CONFIG={"backend":{"consul":{"address":"consul:8500", "scheme":"http", "service":"vault-service"}}, "listener":{"tcp":{"address":"0.0.0.0:8200", "tls_disable":"1"}}}'
    #  - 'VAULT_DEV_ROOT_TOKEN_ID=97CFFBCE-18EE-42F7-B60E-E69F3EAE0E32'
      - 'VAULT_ADDR=http://127.0.0.1:8200'
      - "CONSUL_HTTP_TOKEN=${CONSUL_MASTER_TOKEN}"
      - 'VAULT_REDIRECT_ADDR=http://127.0.0.1:8201'
    volumes:
      - vault:/vault/file
    links:
      - consul-master-1:consul
    networks:
      - netgate
  
  loadbalancer:
    image: traefik:v1.3.3-alpine
    command: --web
    ports:
      - 8082:80
      - 8081:8080
    environment:
      - "CONSUL_HTTP_TOKEN=${CONSUL_MASTER_TOKEN}"
    volumes:
      - "./traefik.toml:/traefik.toml"
    links:
      - consul-master-1:consul
    depends_on:
      - consul-master-1
    networks:
      - netgate

  playerdb:
    image: mongo:3.5.9
    command: --auth --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - player-data-db:/data/db
      - player-data-configdb:/data/configdb
    networks:
      - netgate

  monsterdb:
    image: mongo:3.5.9
    command: --auth --bind_ip_all
    ports:
      - 27018:27017
    volumes:
      - monsters-data-db:/data/db
      - monsters-data-configdb:/data/configdb
    networks:
      - netgate


  jaegertracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp 
      - 6831:6831/udp 
      - 6832:6832/udp
      - 5778:5778 
      - 16686:16686 
      - 14268:14268 
    networks:
      - netgate

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
     - 3001:8080
    environment:
     - 'API_URL=http://localhost:8080/swagger/index.json'
    networks: 
     - netgate

networks:
  netgate:
    driver: bridge

volumes:
  consul-1:
  consul-2:
  consul-3:
  vault:
  player-data-db:
  player-data-configdb:
  monsters-data-db:
  monsters-data-configdb:
    