defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[consul]
  endpoint = "consul:8500"
  watch = true
  prefix = "traefik"

[consulCatalog]
  endpoint = "consul:8500"
  domain = "localhost"
  prefix = "traefik-consul"

[web]
  address = ":8081"