version: "3"

services:  
  consul:
    image: consul
    ports:
      - 8500:8500
    networks:
      - netgate

  player:
    image: slavayssiere/player:0.1 
    ports:
      - 8080
    links:
      - consul:consul
      - playerdb:playerdb
    environment:
      - CONSUL_HOST=consul:8500
      - MONGO_HOST=playerdb
    labels:
      - "traefik.backend=player"
      - "traefik.frontend.rule=Host:player.localhost"
    networks:
      - netgate
  

  # playerdb:
  #   image: mariadb:10.3.0
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=my-secret-pw
  #     - MYSQL_DATABASE=player
  #     - MYSQL_USER=myaccount
  #     - MYSQL_PASSWORD=mypassword
  #   networks:
  #     - netgate
  playerdb:
    image: mongo:3.5.9
    ports:
      - 27017:27017
    networks:
      - netgate

  loadbalancer:
    image: traefik
    command: --web --logLevel=DEBUG
    ports:
      - 8082:80
      - 8081:8080
    volumes:
      - "./traefik.toml:/traefik.toml"
    links:
      - consul:consul
    networks:
      - netgate
  
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
     - 9090:9090
    volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    links:
     - consul:consul
     - player:player
     - prom-playerdb:prom-playerdb
    networks:
      - netgate
  
  # prom-playerdb:
  #   image: prom/mysqld-exporter
  #   ports:
  #     - 9104:9104
  #   links:
  #     - playerdb:bdd
  #   depends_on:
  #     - playerdb
  #   environment:
  #     - DATA_SOURCE_NAME="myaccount:mypassword@(bdd:3306)/player"
  #   networks:
  #     - netgate
    
  prom-playerdb:
    image: eses/mongodb_exporter
    command: -mongodb.uri mongodb://bdd:27017
    ports:
      - 9104:9104
    links:
      - playerdb:bdd
    depends_on:
      - playerdb
    networks:
      - netgate

networks:
  netgate:
    driver: bridge